source 'https://rubygems.org'

gem 'awesome_print'
gem 'better_errors'
gem 'gem-browse'
gem 'gem-ctags'
gem 'git-smart', git: 'git@github.com:johnsyweb/git-smart.git',  branch: 'handle-submodules'
gem 'mailcatcher'
gem 'pry'
gem 'rubocop'
gem 'vimgolf'
gem 'zeus'
